# Generated by Django 2.2.11 on 2020-03-29 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wcal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Event',
        ),
    ]
