# Generated by Django 2.2.11 on 2020-05-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcal', '0002_auto_20200329_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
