# Generated by Django 2.2.11 on 2020-05-08 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wcal', '0003_eventdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventDate',
        ),
    ]
